from je_auto_control import *
win32_ctype_keyboard_control.press_key(keyT)
win32_ctype_keyboard_control.press_key(keyE)
win32_ctype_keyboard_control.press_key(keyS)
win32_ctype_keyboard_control.press_key(keyT)
