version: 2.1

orbs:
  win: circleci/windows@2.2.0
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor:
      name: win/default
      shell: cmd.exe
      
    steps:
      - checkout
      - python/load-cache
      - python/save-cache
      - run:
          command: python ./Test/Win32KeyboardTest.py
	  command: pip install -r JEAutoControl
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
