version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-and-test:
    executor:
      name: win/default
      shell: powershell.exe

    steps:
      - checkout
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements.txt
      - run:
          command: python ./test/win32_keyboard_test.py
          name: test

workflows:
  main:
    jobs:
      - build-and-test
